name: test workflow

run-name: Run by @${{ github.actor }}

on: [push,pull_request,workflow_dispatch]


jobs:
  pass-secret-to-workflow:
    uses: ./.github/workflows/test2.yml
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
    

  pass-secret-to-other-repo:
    uses: wangliu-iscas/test2/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }} 

  pass-secret-to-other-owner-repo:
    uses: OERV-RVCI/isorepocheck/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
      
      
  test_matrix:
    runs-on: ubuntu-latest
    env:
        test_return_code: ""
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7]
      fail-fast: ${{ test_matrix.env.test_return_code == 'done' }}
    steps:
      - name: check
        run: |
          echo "running ${{ matrix.wait }}"
          if  [ ${{ matrix.wait }} == 5 ];then
            echo "test_return_code=done" >> $GITHUB_ENV
          else
            echo "test_return_code=running" >> $GITHUB_ENV
          fi
      
      - name: on-cancel
        if: ${{ test_matrix.env.test_return_code  == "done" }}
        run: |
          echo "${{ matrix.wait }} on-cancel"
          
          
          