name: test workflow

run-name: Run by @${{ github.actor }}

on: [push,pull_request,workflow_dispatch]


jobs:
  pass-secret-to-workflow:
    uses: ./.github/workflows/test2.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}