name: test workflow

run-name: Run by @${{ github.actor }}

on: [push,pull_request,workflow_dispatch]
env:
  check_re: ""

jobs:

  pass-secret-to-workflow:
    uses: ./.github/workflows/test2.yml
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
    

  pass-secret-to-other-repo:
    uses: wangliu-iscas/test2/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }} 

  pass-secret-to-other-owner-repo:
    uses: OERV-RVCI/isorepocheck/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
      
      
  test_matrix:
    runs-on: ubuntu-latest
    outputs:
      check_result:  ${{ steps.check.outputs.check_re }}
    continue-on-error: false
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7]
      #fail-fast: ${{ github.env.test_return_code == 'done'}}
    steps:
      - name: check
        id: check
        if: ${{ env.check_re != 'done' }}
        run: |
          echo "running ${{ matrix.wait }}"
          if [ ${{ matrix.wait }} -le 5 ];then
            echo "check_re=running" >> "$GITHUB_OUTPUT"
          elif [ ${{ matrix.wait }} -eq 5 ];then
            echo "check_re=done" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi

  test_collect_result:
    runs-on: ubuntu-latest
    needs: [test_matrix]
    if: ${{ needs.test_matrix.outputs.check_result  == 'done' }}
    steps:  
      - name: collect_result
        run: |
          echo "check return : ${{ needs.test_matrix.outputs.check_result }}"
          echo "${{ github. test_matrix.strategy.matrix.wait }} on-cancel"
          
          