name: test workflow

run-name: Run by @${{ github.actor }}

on: [push,pull_request,workflow_dispatch]
env:
  test_return_code: "asd"

jobs:
  pass-secret-to-workflow:
    uses: ./.github/workflows/test2.yml
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
    

  pass-secret-to-other-repo:
    uses: wangliu-iscas/test2/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }} 

  pass-secret-to-other-owner-repo:
    uses: OERV-RVCI/isorepocheck/.github/workflows/test.yml@main
    secrets:
      token: ${{ secrets.TEST1_TOKEN }}
      
      
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        wait: [1,2,3,4,5,6,7]
      fail-fast: ${{ github.env.test_return_code == 'done'}}
    steps:
      - name: check
        run: |
          echo "test return code: ${{ env.test_return_code }}"
          echo "running ${{ matrix.wait }}"
          if  [ ${{ matrix.wait }} == 5 ];then
            echo "test_return_code=done" >> $GITHUB_ENV
          else
            echo "test_return_code=running" >> $GITHUB_ENV
          fi
      
      - name: on-cancel
        run: |
          echo "test return code: ${{ env.test_return_code }}"
          echo "${{ matrix.wait }} on-cancel"
          
          
          